#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

# clean case...
cleanCase0

# initialize open.foam...
touch open.foam

#------------------------------------------------------------------------------
